language: java

jdk:
  - oraclejdk7
  - openjdk6


install:
        - integration-tests/setup_sonar.sh

before_script:
        - cp integration-tests/sitedefs_sample.py integration-tests/sitedefs.py
        - sudo pip install requests

script:
        - mvn install -DskipTests=true
        - mvn test
        - RAILS_ENV=production PATH=$PATH:/tmp/sonar-runner-2.4/bin integration-tests/smoketest
